name: GitHub Actions

on:
  label:
    types:
      - edited
  push:
    paths:
      - '<-----DATE----->/**'
      - '!.github/workflows/actions.yml'
      - '!<-----DATE----->/tests/**'
      - '!<-----DATE----->/README.md'

jobs:
  <-----JOBS----->:
    if: contains(github.event.head_commit.message, '<-----COMMIT_MESSAGE----->')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
